--fuel
Furnace.Inject["Base.Charcoal"] = { Fuelprice = 2000 } --Charcoal
Furnace.Inject["Base.Log"] = { Fuelprice = 200 } --Log
Furnace.Inject["Base.LogStacks2"] = { Fuelprice = 405 } --LogStacks
Furnace.Inject["Base.LogStacks3"] = { Fuelprice = 610 } --LogStacks
Furnace.Inject["Base.LogStacks4"] = { Fuelprice = 810 } --LogStacks
Furnace.Inject["Base.UnusableWood"] = { Fuelprice = 35 } --UnusableWood
Furnace.Inject["Base.Plank"] = { Fuelprice = 50 } --Plank
Furnace.Inject["Base.PercedWood"] = { Fuelprice = 45 } --PercedWood
Furnace.Inject["Base.PlankNail"] = { Fuelprice = 40, Material1price = 10 } --PlankNail
Furnace.Inject["Base.Rope"] = { Fuelprice = 5 } --Rope
Furnace.Inject["Base.TreeBranch"] = { Fuelprice = 30 } --TreeBranch
Furnace.Inject["Base.WoodenStick"] = { Fuelprice = 4 } --WoodenStick
Furnace.Inject["Base.WoodenLance"] = { Fuelprice = 5 } --WoodenSLance
Furnace.Inject["Base.RippedSheets"] = { Fuelprice = 1 } --RippedSheets
Furnace.Inject["Base.AlcoholRippedSheets"] = { Fuelprice = 2 } --AlcoholRippedSheets
Furnace.Inject["Base.RippedSheetsDirty"] = { Fuelprice = 1 } --RippedSheetsDirty
Furnace.Inject["Base.Sheet"] = { Fuelprice = 4 } --Sheet
Furnace.Inject["Base.SheetRope"] = { Fuelprice = 4 } --SheetRope
Furnace.Inject["Base.LeatherStrips"] = { Fuelprice = 3 } --LeatherStrips
Furnace.Inject["Base.LeatherStripsDirty"] = { Fuelprice = 2 } --LeatherStripsDirty
Furnace.Inject["Base.DenimStrips"] = { Fuelprice = 3 } --DenimStrips
Furnace.Inject["Base.DenimStripsDirty"] = { Fuelprice = 2 } --DenimStripsDirty
Furnace.Inject["Base.Bandage"] = { Fuelprice = 4 } --Bandage
Furnace.Inject["Base.AlcoholBandage"] = { Fuelprice = 5 } --AlcoholBandage
Furnace.Inject["Base.BandageDirty"] = { Fuelprice = 3 } --BandageDirty
Furnace.Inject["Base.Splint"] = { Fuelprice = 5 } --Splint
-- metal
Furnace.Inject["Base.EngineParts"] = { Material1price = 40 } --EngineParts
Furnace.Inject["Base.OldBrake1"] = { Material1price = 300 } --Brack
Furnace.Inject["Base.OldBrake2"] = { Material1price = 300 } --Brack
Furnace.Inject["Base.OldBrake3"] = { Material1price = 300 } --Brack
Furnace.Inject["Base.NormalBrake1"] = { Material1price = 300 } --Brack
Furnace.Inject["Base.NormalBrake2"] = { Material1price = 300 } --Brack
Furnace.Inject["Base.NormalBrake3"] = { Material1price = 300 } --Brack
Furnace.Inject["Base.ModernBrake1"] = { Material1price = 300 } --Brack
Furnace.Inject["Base.ModernBrake2"] = { Material1price = 300 } --Brack
Furnace.Inject["Base.ModernBrake3"] = { Material1price = 300 } --Brack
Furnace.Inject["Base.FrontCarDoor1"] = { Material1price = 1000 } --Door
Furnace.Inject["Base.FrontCarDoor2"] = { Material1price = 1000 } --Door
Furnace.Inject["Base.FrontCarDoor3"] = { Material1price = 1000 } --Door
Furnace.Inject["Base.RearCarDoor1"] = { Material1price = 1000 } --Door
Furnace.Inject["Base.RearCarDoor2"] = { Material1price = 1000 } --Door
Furnace.Inject["Base.RearCarDoor3"] = { Material1price = 1000 } --Door
Furnace.Inject["Base.RearCarDoorDouble1"] = { Material1price = 2000 } --Door
Furnace.Inject["Base.RearCarDoorDouble2"] = { Material1price = 2000 } --Door
Furnace.Inject["Base.RearCarDoorDouble3"] = { Material1price = 2000 } --Door
Furnace.Inject["Base.SmallGasTank1"] = { Material1price = 1100 } --FuelTank
Furnace.Inject["Base.SmallGasTank2"] = { Material1price = 1400 } --FuelTank
Furnace.Inject["Base.SmallGasTank3"] = { Material1price = 1000 } --FuelTank
Furnace.Inject["Base.NormalGasTank1"] = { Material1price = 1300 } --FuelTank
Furnace.Inject["Base.NormalGasTank2"] = { Material1price = 1700 } --FuelTank
Furnace.Inject["Base.NormalGasTank3"] = { Material1price = 1200 } --FuelTank
Furnace.Inject["Base.BigGasTank1"] = { Material1price = 1500 } --FuelTank
Furnace.Inject["Base.BigGasTank2"] = { Material1price = 2200 } --FuelTank
Furnace.Inject["Base.BigGasTank3"] = { Material1price = 1400 } --FuelTank
Furnace.Inject["Base.EngineDoor1"] = { Material1price = 1500 } --EngineDoor
Furnace.Inject["Base.EngineDoor2"] = { Material1price = 1500 } --EngineDoor
Furnace.Inject["Base.EngineDoor3"] = { Material1price = 1500 } --EngineDoor
Furnace.Inject["Base.OldCarMuffler1"] = { Material1price = 1000 } --Muffler
Furnace.Inject["Base.OldCarMuffler2"] = { Material1price = 1000 } --Muffler
Furnace.Inject["Base.OldCarMuffler3"] = { Material1price = 1000 } --Muffler
Furnace.Inject["Base.NormalCarMuffler1"] = { Material1price = 1000 } --Muffler
Furnace.Inject["Base.NormalCarMuffler2"] = { Material1price = 1000 } --Muffler
Furnace.Inject["Base.NormalCarMuffler3"] = { Material1price = 1000 } --Muffler
Furnace.Inject["Base.ModernCarMuffler1"] = { Material1price = 1000 } --Muffler
Furnace.Inject["Base.ModernCarMuffler2"] = { Material1price = 1000 } --Muffler
Furnace.Inject["Base.ModernCarMuffler3"] = { Material1price = 1000 } --Muffler
Furnace.Inject["Base.NormalSuspension1"] = { Material1price = 200 } --Suspension
Furnace.Inject["Base.NormalSuspension2"] = { Material1price = 200 } --Suspension
Furnace.Inject["Base.NormalSuspension3"] = { Material1price = 200 } --Suspension
Furnace.Inject["Base.ModernSuspension1"] = { Material1price = 300 } --Suspension
Furnace.Inject["Base.ModernSuspension2"] = { Material1price = 300 } --Suspension
Furnace.Inject["Base.ModernSuspension3"] = { Material1price = 300 } --Suspension
Furnace.Inject["Base.OldTire1"] = { Material1price = 800 } --Tire
Furnace.Inject["Base.OldTire2"] = { Material1price = 800 } --Tire
Furnace.Inject["Base.OldTire3"] = { Material1price = 800 } --Tire
Furnace.Inject["Base.NormalTire1"] = { Material1price = 800 } --Tire
Furnace.Inject["Base.NormalTire2"] = { Material1price = 800 } --Tire
Furnace.Inject["Base.NormalTire3"] = { Material1price = 800 } --Tire
Furnace.Inject["Base.ModernTire1"] = { Material1price = 800 } --Tire
Furnace.Inject["Base.ModernTire2"] = { Material1price = 800 } --Tire
Furnace.Inject["Base.ModernTire3"] = { Material1price = 800 } --Tire
Furnace.Inject["Base.TrunkDoor1"] = { Material1price = 800 } --TrunkDoor
Furnace.Inject["Base.TrunkDoor2"] = { Material1price = 800 } --TrunkDoor
Furnace.Inject["Base.TrunkDoor3"] = { Material1price = 800 } --TrunkDoor

Furnace.Inject["Base.FurnaceIronIngot"] = { Material1price = 10000 } --FurnaceIronIngot
Furnace.Inject["Base.BarbedWire"] = { Material1price = 500 } --BarbedWire
Furnace.Inject["Base.NailsBox"] = { Material1price = 800 } --NailsBox
Furnace.Inject["Base.PaperclipBox"] = { Material1price = 500 } --PaperclipBox
Furnace.Inject["Base.ScrewsBox"] = { Material1price = 900 } --ScrewsBox
Furnace.Inject["Base.Hinge"] = { Material1price = 100 } --Hinge
Furnace.Inject["Base.Doorknob"] = { Material1price = 150 } --Doorknob
Furnace.Inject["Base.PaintbucketEmpty"] = { Material1price = 200 } --PaintbucketEmpty
Furnace.Inject["Base.TinCanEmpty"] = { Material1price = 2 } --TinCanEmpty
Furnace.Inject["Base.SheetMetal"] = { Material1price = 500 } --SheetMetal
Furnace.Inject["Base.SmallSheetMetal"] = { Material1price = 100 } --SmallSheetMetal
Furnace.Inject["Base.Pipe"] = { Material1price = 300 } --Pipe
Furnace.Inject["Base.Nails"] = { Material1price = 8 } --Nails
Furnace.Inject["Base.Paperclip"] = { Material1price = 5 } --Paperclip
Furnace.Inject["Base.Screws"] = { Material1price = 9 } --ScrewsBox
Furnace.Inject["Base.ScrapMetal"] = { Material1price = 50 } --ScrapMetal
Furnace.Inject["Base.Staples"] = { Material1price = 100 } --Staples
Furnace.Inject["Base.UnusableMetal"] = { Material1price = 300 } --UnusableMetal
Furnace.Inject["Base.Wire"] = { Material1price = 10 } --Wire
Furnace.Inject["Base.BeerCanEmpty"] = { Material1price = 2 } --BeerCanEmpty
Furnace.Inject["Base.PopEmpty"] = { Material1price = 2 } --PopEmpty
Furnace.Inject["Base.Pop2Empty"] = { Material1price = 2 } --Pop2Empty
Furnace.Inject["Base.Pop3Empty"] = { Material1price = 2 } --Pop3Empty
-- gold
Furnace.Inject["Base.FurnaceGolgIngot"] = { Material2price = 1000 } --GolgIngot
Furnace.Inject["Base.Necklace_Gold"] = { Material2price = 100 } --Necklace
Furnace.Inject["Base.Necklace_GoldRuby"] = { Material2price = 100 } --Necklace
Furnace.Inject["Base.Necklace_GoldDiamond"] = { Material2price = 100 } --Necklace
Furnace.Inject["Base.NecklaceLong_Gold"] = { Material2price = 150 } --Necklace
Furnace.Inject["Base.NecklaceLong_GoldDiamond"] = { Material2price = 150 } --Necklace
Furnace.Inject["Base.NoseRing_Gold"] = { Material2price = 50 } --NoseRing
Furnace.Inject["Base.NoseStud_Gold"] = { Material2price = 50 } --NoseRing
Furnace.Inject["Base.Earring_LoopLrg_Gold"] = { Material2price = 70 } --Earring
Furnace.Inject["Base.Earring_LoopMed_Gold"] = { Material2price = 50 } --Earring
Furnace.Inject["Base.Earring_LoopSmall_Gold_Both"] = { Material2price = 50 } --Earring
Furnace.Inject["Base.Earring_LoopSmall_Gold_Top"] = { Material2price = 50 } --Earring
Furnace.Inject["Base.Earring_Stud_Gold"] = { Material2price = 50 } --Earring
Furnace.Inject["Base.Ring_Right_MiddleFinger_Gold"] = { Material2price = 50 } --Ring
Furnace.Inject["Base.Ring_Left_MiddleFinger_Gold"] = { Material2price = 50 } --Ring
Furnace.Inject["Base.Ring_Right_RingFinger_Gold"] = { Material2price = 50 } --Ring
Furnace.Inject["Base.Ring_Left_RingFinger_Gold"] = { Material2price = 50 } --Ring
Furnace.Inject["Base.Ring_Right_MiddleFinger_GoldRuby"] = { Material2price = 50 } --Ring
Furnace.Inject["Base.Ring_Left_MiddleFinger_GoldRuby"] = { Material2price = 50 } --Ring
Furnace.Inject["Base.Ring_Right_RingFinger_GoldRuby"] = { Material2price = 50 } --Ring
Furnace.Inject["Base.Ring_Left_RingFinger_GoldRuby"] = { Material2price = 50 } --Ring
Furnace.Inject["Base.Ring_Right_MiddleFinger_GoldDiamond"] = { Material2price = 50 } --Ring
Furnace.Inject["Base.Ring_Left_MiddleFinger_GoldDiamond"] = { Material2price = 50 } --Ring
Furnace.Inject["Base.Ring_Right_RingFinger_GoldDiamond"] = { Material2price = 50 } --Ring
Furnace.Inject["Base.Ring_Left_RingFinger_GoldDiamond"] = { Material2price = 50 } --Ring
Furnace.Inject["Base.Bracelet_BangleRightGold"] = { Material2price = 80 } --Bracelet
Furnace.Inject["Base.Bracelet_BangleLeftGold"] = { Material2price = 80 } --Bracelet
Furnace.Inject["Base.Bracelet_ChainRightGold"] = { Material2price = 70 } --Chain
Furnace.Inject["Base.Bracelet_ChainLeftGold"] = { Material2price = 70 } --Chain
Furnace.Inject["Base.BellyButton_DangleGold"] = { Material2price = 50 } --BellyButton
Furnace.Inject["Base.BellyButton_DangleGoldRuby"] = { Material2price = 50 } --BellyButton
Furnace.Inject["Base.BellyButton_RingGold"] = { Material2price = 50 } --BellyButton
Furnace.Inject["Base.BellyButton_RingGoldDiamond"] = { Material2price = 50 } --BellyButton
Furnace.Inject["Base.BellyButton_RingGoldRuby"] = { Material2price = 50 } --BellyButton
Furnace.Inject["Base.BellyButton_StudGold"] = { Material2price = 50 } --BellyButton
Furnace.Inject["Base.BellyButton_StudGoldDiamond"] = { Material2price = 50 } --BellyButton
Furnace.Inject["Base.WristWatch_Right_ClassicGold"] = { Material2price = 150 } --WristWatch
Furnace.Inject["Base.WristWatch_Left_ClassicGold"] = { Material2price = 150 } --WristWatch
-- silver
Furnace.Inject["Base.FurnaceSilverIngot"] = { Material3price = 1000 } --Ingot
Furnace.Inject["Base.Necklace_Silver"] = { Material3price = 100 } --Necklace
Furnace.Inject["Base.Necklace_SilverSapphire"] = { Material3price = 100 } --Necklace
Furnace.Inject["Base.Necklace_SilverCrucifix"] = { Material3price = 100 } --Necklace
Furnace.Inject["Base.Necklace_SilverDiamond"] = { Material3price = 100 } --Necklace
Furnace.Inject["Base.NecklaceLong_Silver"] = { Material3price = 150 } --Necklace
Furnace.Inject["Base.NecklaceLong_SilverEmerald"] = { Material3price = 150 } --Necklace
Furnace.Inject["Base.NecklaceLong_SilverSapphire"] = { Material3price = 150 } --Necklace
Furnace.Inject["Base.NecklaceLong_SilverDiamond"] = { Material3price = 150 } --Necklace
Furnace.Inject["Base.NoseRing_Silver"] = { Material3price = 50 } --NoseRing
Furnace.Inject["Base.NoseStud_Silver"] = { Material3price = 50 } --NoseRing
Furnace.Inject["Base.Earring_LoopLrg_Silver"] = { Material3price = 70 } --Earring
Furnace.Inject["Base.Earring_LoopMed_Silver"] = { Material3price = 50 } --Earring
Furnace.Inject["Base.Earring_LoopSmall_Silver_Both"] = { Material3price = 50 } --Earring
Furnace.Inject["Base.Earring_LoopSmall_Silver_Top"] = { Material3price = 50 } --Earring
Furnace.Inject["Base.Earring_Stud_Silver"] = { Material3price = 50 } --Earring
Furnace.Inject["Base.Ring_Right_MiddleFinger_Silver"] = { Material3price = 50 } --Ring
Furnace.Inject["Base.Ring_Left_MiddleFinger_Silver"] = { Material3price = 50 } --Ring
Furnace.Inject["Base.Ring_Right_RingFinger_Silver"] = { Material3price = 50 } --Ring
Furnace.Inject["Base.Ring_Left_RingFinger_Silver"] = { Material3price = 50 } --Ring
Furnace.Inject["Base.Ring_Right_MiddleFinger_SilverDiamond"] = { Material3price = 50 } --Ring
Furnace.Inject["Base.Ring_Left_MiddleFinger_SilverDiamond"] = { Material3price = 50 } --Ring
Furnace.Inject["Base.Ring_Right_RingFinger_SilverDiamond"] = { Material3price = 50 } --Ring
Furnace.Inject["Base.Ring_Left_RingFinger_SilverDiamond"] = { Material3price = 50 } --Ring
Furnace.Inject["Base.Bracelet_BangleRightSilver"] = { Material3price = 80 } --Bracelet
Furnace.Inject["Base.Bracelet_BangleLeftSilver"] = { Material3price = 80 } --Bracelet
Furnace.Inject["Base.Bracelet_ChainRightSilver"] = { Material3price = 70 } --Bracelet
Furnace.Inject["Base.Bracelet_ChainLeftSilver"] = { Material3price = 70 } --Bracelet
Furnace.Inject["Base.BellyButton_DangleSilver"] = { Material3price = 50 } --BellyButton
Furnace.Inject["Base.BellyButton_DangleSilverDiamond"] = { Material3price = 50 } --BellyButton
Furnace.Inject["Base.BellyButton_RingSilver"] = { Material3price = 50 } --BellyButton
Furnace.Inject["Base.BellyButton_RingSilverAmethyst"] = { Material3price = 50 } --BellyButton
Furnace.Inject["Base.BellyButton_RingSilverDiamond"] = { Material3price = 50 } --BellyButton
Furnace.Inject["Base.BellyButton_RingSilverRuby"] = { Material3price = 50 } --BellyButton
Furnace.Inject["Base.BellyButton_StudSilver"] = { Material3price = 50 } --BellyButton
Furnace.Inject["Base.BellyButton_StudSilverDiamond"] = { Material3price = 50 } --BellyButton
-- glass
Furnace.Inject["Base.Windshield1"] = { Material4price = 800 } --Windshield
Furnace.Inject["Base.Windshield2"] = { Material4price = 800 } --Windshield
Furnace.Inject["Base.Windshield3"] = { Material4price = 800 } --Windshield
Furnace.Inject["Base.RearWindshield1"] = { Material4price = 800 } --RearWindshield
Furnace.Inject["Base.RearWindshield2"] = { Material4price = 800 } --RearWindshield
Furnace.Inject["Base.RearWindshield3"] = { Material4price = 800 } --RearWindshield
Furnace.Inject["Base.RearWindow1"] = { Material4price = 300 } --RearWindow
Furnace.Inject["Base.RearWindow2"] = { Material4price = 300 } --RearWindow
Furnace.Inject["Base.RearWindow3"] = { Material4price = 300 } --RearWindow
Furnace.Inject["Base.FrontWindow1"] = { Material4price = 300 } --FrontWindow
Furnace.Inject["Base.FrontWindow2"] = { Material4price = 300 } --FrontWindow
Furnace.Inject["Base.FrontWindow3"] = { Material4price = 300 } --FrontWindow